### ISSUE TITLE
ESPHome 2024.3.0 update issues

### ISSUE THREAD

**Issue by jeremiahsb** [LoopOnCode/UnitySensor#20]
Doing an OTA update:
Linking .pioenvs/unity-b9b2e4/firmware.elf
RAM:   [==        ]  17.7% (used 57892 bytes from 327680 bytes)
Flash: [==========]  98.6% (used 1809334 bytes from 1835008 bytes)
Building .pioenvs/unity-b9b2e4/firmware.bin
Creating esp32c3 image...
Successfully created esp32c3 image.
esp32_create_combined_bin([".pioenvs/unity-b9b2e4/firmware.bin"], [".pioenvs/unity-b9b2e4/firmware.elf"])
Wrote 0x1d88f0 bytes to file /data/build/unity-b9b2e4/.pioenvs/unity-b9b2e4/firmware-factory.bin, ready to flash to offset 0x0
======================== [SUCCESS] Took 106.35 seconds ========================
INFO Successfully compiled program.
INFO Connecting to 192.168.90.84
INFO Uploading /data/build/unity-b9b2e4/.pioenvs/unity-b9b2e4/firmware.bin (1870064 bytes)
ERROR Error binary size: Error: The OTA partition on the ESP is too small. ESPHome needs to resize this partition, please flash over USB.

Flashing via USB results in this in the log:
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fcd6100,len:0x38c
load:0x403ce000,len:0x6ac
load:0x403d0000,len:0x24e4
entry 0x403ce000
ESP-ROM:esp32c3-api1-20210207
Build:Feb  7 2021
rst:0x3 (RTC_SW_SYS_RST),boot:0xc (SPI_FAST_FLASH_BOOT)
Saved PC:0x403d10fc

The device doesn't even try to connect to the network. I had to go through the USB logging to get the output.

**Comment by davlaw** [comment]
Same here, but was lucky to have a bin file from a few months ago to re-flash to working state

**Comment by jeremiahsb** [comment]
I came across this addon that enables you to load up older versions of ESPHome. I was able to roll back to the prior version and everything works fine.

https://github.com/khenderick/esphome-legacy-addons

**Comment by davlaw** [comment]
Thanks, got it added. While I have not used it it nice to know its there

**Comment by Sawadee2u** [comment]
Having same issue with updating Unity Sensor Board with ESPHome.

Updating /config/esphome/unity-1478e8.yaml
------------------------------------------------------------

INFO ESPHome 2024.3.0
INFO Reading configuration /config/esphome/unity-1478e8.yaml...
WARNING GPIO2 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
WARNING GPIO9 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
INFO Generating C++ source...
INFO Compiling app...
Processing unity-1478e8 (board: esp32-c3-devkitm-1; framework: arduino; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32C3 160MHz, 320KB RAM, 4MB Flash
 - toolchain-riscv32-esp @ 8.4.0+2021r2-patch5
Dependency Graph
|-- AsyncTCP-esphome @ 2.1.3
|-- WiFi @ 2.0.0
|-- FS @ 2.0.0
|-- Update @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 3.1.0
|-- DNSServer @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- noise-c @ 0.1.4
|-- Wire @ 2.0.0
|-- NeoPixelBus @ 2.7.3
|-- Improv @ 1.2.3
RAM:   [==        ]  17.7% (used 57892 bytes from 327680 bytes)
Flash: [==========]  98.6% (used 1809350 bytes from 1835008 bytes)
========================= [SUCCESS] Took 4.67 seconds =========================
INFO Successfully compiled program.
INFO Resolving IP address of unity-1478e8.local
INFO  -> 192.168.123.202
INFO Uploading /data/build/unity-1478e8/.pioenvs/unity-1478e8/firmware.bin (1870080 bytes)
ERROR Error binary size: Error: The OTA partition on the ESP is too small. ESPHome needs to resize this partition, please flash over USB.
======== [ERROR] /config/esphome/unity-1478e8.yaml ========



======================== [SUMMARY] ========================
  - /config/esphome/olimex-bluetooth-proxy-03362c.yaml: SUCCESS
  - /config/esphome/olimex-bluetooth-proxy-c25dfc.yaml: SUCCESS
  - /config/esphome/unity-1478e8.yaml: FAILED
